In [169]:
import pandas as pd
import plotly as px

In [170]:
import plotly.io as pio

pio.renderers.default = 'plotly_mimetype+notebook_connected'

<div style="text-align:center;">
    <h1> Analyse actuelle des risques et de la rentabilite des assurés</h1>
</div>

In [171]:
data_assurance = pd.read_csv("assurance_data_1000.csv", sep=";")

data_assurance.head()

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21

In [172]:
data_assurance.shape # cést la dimention de la base de donne

(1000, 11)

In [173]:
data_assurance.dtypes # c'est le type de chaque colonne dans la base de données

id_assure                   int64
age                         int64
sexe                          str
type_assurance                str
duree_contrat               int64
montant_prime             float64
nb_sinistres                int64
montant_sinistres         float64
date_derniere_sinistre        str
region                        str
bonus_malus               float64
dtype: object

In [174]:
data_assurance.isnull().sum().sum() # c'est pour verifier s'il y a des valeurs manquantes dans la base de données

np.int64(0)

In [175]:
int(data_assurance.isnull().sum().sum()) # le nombre de valeurs manquantes dans la base de données

0

In [176]:
data_assurance.isnull().sum()

id_assure                 0
age                       0
sexe                      0
type_assurance            0
duree_contrat             0
montant_prime             0
nb_sinistres              0
montant_sinistres         0
date_derniere_sinistre    0
region                    0
bonus_malus               0
dtype: int64

distribution de l'age

In [177]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[go.Histogram(x=data_assurance["age"])],
)

fig.update_layout(
    title="Histogramme des âges",
    bargap=0.2  # espace entre les barres (0 à 1)
)

fig.show()

In [178]:
# Créer une nouvelle variable dans le DataFrame

def define_tranche_age(age):
    if age < 20:
        return "<20"
    elif 20 <= age < 30:
        return "20-30"
    elif 30 <= age < 40:
        return "30-40"
    elif 40 <= age < 50:
        return "40-50"
    elif 50 <= age < 60:
        return "50-60"
    else:
        return ">=60"

data_assurance["tranche_age"] = data_assurance["age"].apply(define_tranche_age)
data_assurance.head()

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus,tranche_age
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69,50-60
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33,>=60
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06,40-50
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26,30-40
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21,>=60

In [179]:
data_assurance_grouped = data_assurance["tranche_age"].value_counts().reset_index(name="frequence")
data_assurance_grouped

  tranche_age  frequence
0        >=60        344
1       40-50        175
2       50-60        167
3       20-30        142
4       30-40        136
5         <20         36

In [180]:
fig = go.Figure(
    data=[
        go.Bar(
            x=data_assurance_grouped["tranche_age"],
            y=data_assurance_grouped["frequence"],
            text=data_assurance_grouped["tranche_age"],  # texte au-dessus
            textposition="outside"
        )
    ]
)

fig.update_layout(
    title="Répartition des assurés par tranche d'âge",
    xaxis_title="Tranches d'âge",
    yaxis_title="Fréquence",
    bargap=0.2
)

fig.show()

la repartition des tranches d'age si dessou nous montre que les personnes ages sont plus interesse aux produits de l'assureur
pour ce type de graph donner des recommandations

répartition hommes / femmes

In [181]:
repartition_sexe = data_assurance["sexe"].value_counts().reset_index(name="frequence")
repartition_sexe.columns = ["sexe", "frequence"]

In [182]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Bar(
            x=repartition_sexe["sexe"],
            y=repartition_sexe["frequence"],
            text=repartition_sexe["frequence"],
            textposition="outside"
        )
    ]
)

fig.update_layout(
    title="Répartition hommes / femmes",
    xaxis_title="Sexe",
    yaxis_title="Nombre",
    bargap=0.3
)

fig.show()

In [183]:
fig = go.Figure(
    data=[
        go.Pie(
            labels=repartition_sexe["sexe"],
            values=repartition_sexe["frequence"],
            textinfo="label+percent"
        )
    ]
)

fig.update_layout(title="Répartition hommes / femmes")

fig.show()

Répartition par type d’assurance

In [184]:
repartition_assurance = data_assurance["type_assurance"].value_counts().reset_index(name="frequence")
repartition_assurance.columns = ["type_assurance", "frequence"]

In [185]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Bar(
            x=repartition_assurance["type_assurance"],
            y=repartition_assurance["frequence"],
            text=repartition_assurance["frequence"],
            textposition="outside"
        )
    ]
)

fig.update_layout(
    title="Répartition par type d'assurance",
    xaxis_title="Type d'assurance",
    yaxis_title="Nombre d'assurés",
    bargap=0.3
)

fig.show()

Analyse des sinistres

 Quel type dássurance genere le plus de sinistre

In [186]:
data_sinistre_grouped = data_assurance.groupby("type_assurance")["nb_sinistres"].sum().reset_index(name="total_sinistre")
data_sinistre_grouped

  type_assurance  total_sinistre
0           Auto             114
1     Habitation             108
2          Santé             138
3            Vie             124

Nombre total de sinistres par tranche d’âge

In [187]:
data_assurance["profit_client"] = (data_assurance["montant_prime"] - data_assurance["montant_sinistres"])

data_assurance["rentabilite"] = data_assurance["profit_client"].apply(lambda x: "Rentable" if x > 0 else "Non rentable")

rentabilite_clients = (data_assurance["rentabilite"].value_counts().reset_index(name="Effectif"))

In [188]:
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Bar(
            x=rentabilite_clients["rentabilite"],
            y=rentabilite_clients["Effectif"],
            textposition="outside"
        )
    ]
)

fig_rentabilite.update_traces(textposition="outside", textfont_size=12)
fig_rentabilite.update_layout(
    bargap=0.2,
    xaxis_title="Statut de rentabilité",
    yaxis_title="Nombre de clients",
    showlegend=False
)

fig_rentabilite.show()

In [189]:
profit_par_assurance = (
    data_assurance
    .groupby("type_assurance")["profit_client"]
    .sum()
    .reset_index(name="profit_total")
)

fig = go.Figure(
    data=[go.Bar(
        x=profit_par_assurance["type_assurance"],
        y=profit_par_assurance["profit_total"],
        text=profit_par_assurance["profit_total"],
        textposition="outside"
    )]
)

fig.update_layout(
    title="Rentabilité par type d'assurance",
    xaxis_title="Type d'assurance",
    yaxis_title="Profit total",
    bargap=0.3
)

fig.show()