<div style="text-align:center; color: yellow;"> 
    <h1> Analyse actuarielle des risque et de la rentabilité des assurés </h1>
</div>

In [2]:
#============================== LIBRAIRIES ======================
import pandas as pd;
import plotly;

In [1]:
import plotly.io as pio

pio.renderers.default = 'plotly_mimetype+notebook_connected'

In [3]:
#============================== Importer les donnees ======================
data_assurance = pd.read_csv('assurance_data_1000.csv', sep=';')

In [4]:
# Voir les 5 premieres donnees
data_assurance.head(5)

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21

In [5]:
# Voir les dimensions de la base de donnees
data_assurance.shape

(1000, 11)

In [6]:
# Voir les types des nos variables
data_assurance.dtypes

id_assure                   int64
age                         int64
sexe                          str
type_assurance                str
duree_contrat               int64
montant_prime             float64
nb_sinistres                int64
montant_sinistres         float64
date_derniere_sinistre        str
region                        str
bonus_malus               float64
dtype: object

In [7]:
# Voir le nombre devaleurs manquantes par variable
data_assurance.isna().sum()

id_assure                 0
age                       0
sexe                      0
type_assurance            0
duree_contrat             0
montant_prime             0
nb_sinistres              0
montant_sinistres         0
date_derniere_sinistre    0
region                    0
bonus_malus               0
dtype: int64

In [8]:
# Voir le nombre total de valeurs manquantes
int(data_assurance.isna().sum().sum())

0

# 1. Analyse exploratoire de données (EDA)

## **La distribution de l'âge**

In [9]:
# Créer un histogramme pour la distribution de l'âge
import plotly.express as px

fig_age = px.histogram(data_assurance, x="age", title="Distribution des âges", labels={"age": "Tranche d'âge"})
fig_age.update_layout(bargap=0.1,yaxis_title="Fréquence d'âge") # ajuster l'espacement entre les barres de l'histogramme et le titre de l'axe y
fig_age.show()

A partir d'ici nous ne pouvons tirer de conclusion globale donc nous créerons une variable tranche d'âge pour la suite de la distribution

In [10]:
# Creer ue nouvelle variable dans le data_frame 

def define_tranche_age(age):
    if age < 20 :
        return '<20'
    elif age >=20 and age <30 :
        return '20-30' 
    elif age >=30 and age <40 :
        return '30-40' 
    elif age >=40 and age <50 :
        return '40-50' 
    elif age >=50 and age <60 :
        return '50-60'
    else: 
        return '>=60' 

data_assurance["tranche_age"] = data_assurance["age"].apply(define_tranche_age)

In [11]:
data_assurance.head(10)

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus,tranche_age
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69,50-60
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33,>=60
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06,40-50
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26,30-40
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21,>=60
5,6,25,feminin,Vie,2,1624.91,0,4173.95,2024-09-23 14:51:34.070539,Thiès,0.71,20-30
6,7,78,masculin,Vie,4,1186.89,0,3768.67,2023-06-08 14:51:34.070543,Thiès,1.07,>=60
7,8,38,masculin,Santé,5,1074.07,0,8759.05,2021-11-26 14:51:34.070547,Thiès,1.37,30-40
8,9,56,masculin,Habitation,4,657.63,0,9052.99,2021-05-14 14:51:34.070557,Kaolack,0.93,50-60
9,10,75,masculin,Habitation,3,1870.33,0,4929.57,2025-10-25 14:51:34.070560,Thiès,1.47,>=60

In [12]:
data_assurance_grouped_age = data_assurance["tranche_age"].value_counts().reset_index(name="frequence")

In [13]:
data_assurance_grouped_age

  tranche_age  frequence
0        >=60        344
1       40-50        175
2       50-60        167
3       20-30        142
4       30-40        136
5         <20         36

In [14]:
fig_age_2 = px.bar(
    data_assurance_grouped_age, 
    x="tranche_age", 
    y="frequence", 
    title="Distribution des tranches d'âge", 
    labels={"tranche_age": "Tranche d'âge"},
    text_auto=True)
fig_age_2.update_layout(yaxis_title="Fréquence d'âge")
fig_age_2.show()

La répartition des tranches d'âges ci-dessus nous montre que les personnes âgées sont plus intéressées aux produits de l'assureur. 
Pour ce type de graphe, donnez des recommandations 

Interpreter = Sortir des messages et recommandations

Recommandation : L'assurance devra orienter ses produits vers les personnes âgés

## **Répartition par sexe**

In [15]:
data_assurance_grouped_sexe = data_assurance["sexe"].value_counts().reset_index(name="frequence")

data_assurance_grouped_sexe.head(10)

       sexe  frequence
0  masculin        523
1   feminin        477

In [16]:
# fig_sexe = px.pie(
#     data_assurance_grouped_sexe, 
#     names="sexe", 
#     values="frequence", 
#     title="Répartition par sexe", 
#     )
fig_sexe = px.bar(
    data_assurance_grouped_sexe, 
    x="sexe", 
    y="frequence", 
    title="Répartition par sexe", 
    labels={"sexe": "Sexe"},
    )
fig_sexe.update_layout(yaxis_title="Fréquence d'âge")
fig_sexe.show()

In [17]:
data_assurance_grouped_type = data_assurance["type_assurance"].value_counts().reset_index(name="frequence")

data_assurance_grouped_type.head(10)

  type_assurance  frequence
0           Auto        261
1          Santé        254
2            Vie        243
3     Habitation        242

In [18]:
# fig_type = px.pie(
#     data_assurance_grouped_type, 
#     names="type_assurance", 
#     values="frequence", 
#     title="Répartition par type d'assurance", 
#     #color_discrete_sequence=px.colors.sequential.Bluered_r
#     )
#fig_type.update_traces(textposition='inside', textinfo='percent+label')
fig_type = px.bar(
    data_assurance_grouped_type, 
    x="type_assurance", 
    y="frequence", 
    title="Répartition par type d'assurance", 
    labels={"type_assurance": "Type d'assurance"},
    )
fig_type.update_layout(yaxis_title="Fréquence d'âge")
fig_type.show()

# 2. Analyse des sinistres

## Quel type d’assurance génère le plus de sinistres ?

In [19]:
data_assurance_grouped_type_sinistre = data_assurance.groupby("type_assurance")["nb_sinistres"].sum().reset_index(name="total_sinistres")

data_assurance_grouped_type_sinistre

  type_assurance  total_sinistres
0           Auto              114
1     Habitation              108
2          Santé              138
3            Vie              124

In [20]:
fig_sinistres = px.bar(
    data_assurance_grouped_type_sinistre, 
    x="type_assurance", 
    y="total_sinistres", 
    title="Répartition de sinistres par type d'assurance", 
    labels={"type_assurance": "Type d'assurance"},
    )
fig_sinistres.update_layout(yaxis_title="Nombre de sinistres")
fig_sinistres.show()

In [21]:
from curses import raw
from IPython.display import display_html

display_html(
    """
    <p style="font-size: 20px;">Au vu de la répartition des sinistres par type d'assurance, L'assurance santé génère le plus de sinistres.</p>
    """, raw=True
)

ModuleNotFoundError: No module named '_curses'

## Les clients plus âgés ont-ils plus de sinistres ?

In [ ]:
data_assurance_grouped_age_sinistre = data_assurance.groupby("tranche_age")["nb_sinistres"].sum().reset_index(name="total_sinistres")

data_assurance_grouped_age_sinistre

  tranche_age  total_sinistres
0       20-30               55
1       30-40               74
2       40-50               71
3       50-60               85
4         <20               18
5        >=60              181

In [ ]:
fig_sinistres_age = px.bar(
    data_assurance_grouped_age_sinistre, 
    x="tranche_age", 
    y="total_sinistres", 
    title="Répartition de sinistres par tranche d'âge", 
    labels={"tranche_age": "Tranche d'âge"},
    )
fig_sinistres_age.update_layout(yaxis_title="Nombre de sinistres")
fig_sinistres_age.show()

In [ ]:
display_html(
    """
    <p style="font-size: 20px;">Au vu de la répartition des sinistres par tranche d'âge, Oui les personnes âgées ont plus de sinistres.</p>
    """, raw=True
)

## Quelles régions ont les sinistres les plus élevés ?

In [ ]:
data_assurance

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus,tranche_age
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69,50-60
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33,>=60
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06,40-50
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26,30-40
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21,>=60
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,18,masculin,Vie,4,227.25,0,281.22,2021-12-25 14:51:34.072774,Thiès,0.93,<20
996,997,35,feminin,Habitation,8,1766.97,1,3753.21,2022-06-02 14:51:34.072777,Kaolack,1.38,30-40
997,998,49,feminin,Auto,1,839.87,1,6267.53,2022-01-11 14:51:34.072778,Dakar,0.80,40-50
998,999,64,masculin,Vie,6,1129.35,0,1460.97,2021-08-19 14:51:34.072781,Saint-Louis,0.59,>=60
999,1000,66,feminin,Habitation,1,1939.33,0,8230.04,2025-10-10 14:51:34.072783,Thiès,1.26,>=60

In [ ]:
data_assurance_grouped_region_sinistre = data_assurance.groupby("region")["nb_sinistres"].sum().reset_index(name="total_sinistres")

data_assurance_grouped_region_sinistre

        region  total_sinistres
0        Dakar              106
1      Kaolack              113
2  Saint-Louis              130
3        Thiès              135

In [ ]:
fig_sinistres_region = px.bar(
    data_assurance_grouped_region_sinistre, 
    x="region", 
    y="total_sinistres", 
    title="Répartition de sinistres par région", 
    labels={"region": "Région"},
    )
fig_sinistres_region.update_layout(yaxis_title="Nombre de sinistres")
fig_sinistres_region.show()

In [ ]:
display_html(
    """
    <p style="font-size: 20px;">Au vu de la répartition des sinistres par région, Thiès est la région qui a le plus de sinistres.</p>
    """, raw=True
)

# 3. Analyse de la rentabilité

In [ ]:
data_assurance["profit_client"] = data_assurance["montant_prime"] - data_assurance["montant_sinistres"]

data_assurance.head(10)

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus,tranche_age,profit_client
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69,50-60,-2221.11
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33,>=60,-165.64
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06,40-50,-1701.47
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26,30-40,-5250.25
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21,>=60,-2169.77
5,6,25,feminin,Vie,2,1624.91,0,4173.95,2024-09-23 14:51:34.070539,Thiès,0.71,20-30,-2549.04
6,7,78,masculin,Vie,4,1186.89,0,3768.67,2023-06-08 14:51:34.070543,Thiès,1.07,>=60,-2581.78
7,8,38,masculin,Santé,5,1074.07,0,8759.05,2021-11-26 14:51:34.070547,Thiès,1.37,30-40,-7684.98
8,9,56,masculin,Habitation,4,657.63,0,9052.99,2021-05-14 14:51:34.070557,Kaolack,0.93,50-60,-8395.36
9,10,75,masculin,Habitation,3,1870.33,0,4929.57,2025-10-25 14:51:34.070560,Thiès,1.47,>=60,-3059.24

## Clients rentables vs non rentables

In [ ]:
data_assurance["rentabilite"] = data_assurance["profit_client"].apply(lambda x: "Rentable" if x > 0 else "Non rentable")

#data_assurance.drop(columns=["is_rentable"], inplace=True)

data_assurance.head(10)

,id_assure,age,sexe,type_assurance,duree_contrat,montant_prime,nb_sinistres,montant_sinistres,date_derniere_sinistre,region,bonus_malus,tranche_age,profit_client,rentabilite
0,1,56,masculin,Habitation,3,114.56,0,2335.67,2023-07-21 14:51:34.070498,Kaolack,0.69,50-60,-2221.11,Non rentable
1,2,69,masculin,Auto,4,516.23,1,681.87,2021-11-04 14:51:34.070527,Saint-Louis,1.33,>=60,-165.64,Non rentable
2,3,46,feminin,Habitation,5,169.77,0,1871.24,2024-01-17 14:51:34.070531,Thiès,1.06,40-50,-1701.47,Non rentable
3,4,32,masculin,Auto,6,305.25,1,5555.50,2023-05-16 14:51:34.070534,Saint-Louis,1.26,30-40,-5250.25,Non rentable
4,5,60,masculin,Habitation,3,743.84,1,2913.61,2025-11-14 14:51:34.070536,Saint-Louis,1.21,>=60,-2169.77,Non rentable
5,6,25,feminin,Vie,2,1624.91,0,4173.95,2024-09-23 14:51:34.070539,Thiès,0.71,20-30,-2549.04,Non rentable
6,7,78,masculin,Vie,4,1186.89,0,3768.67,2023-06-08 14:51:34.070543,Thiès,1.07,>=60,-2581.78,Non rentable
7,8,38,masculin,Santé,5,1074.07,0,8759.05,2021-11-26 14:51:34.070547,Thiès,1.37,30-40,-7684.98,Non rentable
8,9,56,masculin,Habitation,4,657.63,0,9052.99,2021-05-14 14:51:34.070557,Kaolack,0.93,50-60,-8395.36,Non rentable
9,10,75,masculin,Habitation,3,1870.33,0,4929.57,2025-10-25 14:51:34.070560,Thiès,1.47,>=60,-3059.24,Non rentable

In [ ]:
data_assurance_grouped_rentable = data_assurance["rentabilite"].value_counts().reset_index(name="nombre_clients")

data_assurance_grouped_rentable

    rentabilite  nombre_clients
0  Non rentable             904
1      Rentable              96

In [ ]:

fig_rentable = px.bar(
    data_assurance_grouped_rentable, 
    x="rentabilite", 
    y="nombre_clients", 
    title="Répartition de rentabilité par client", 
    labels={"rentabilite": "Rentabilité"},
    text_auto=True,

    )
fig_rentable.update_layout(yaxis_title="Nombre de clients")
fig_rentable.show()

## Rentabilité par type d’assurance

In [ ]:
data_assurance_grouped_rentable_type = data_assurance.groupby("type_assurance")["rentabilite"].value_counts().reset_index(name="nombre_clients")

data_assurance_grouped_rentable_type

  type_assurance   rentabilite  nombre_clients
0           Auto  Non rentable             238
1           Auto      Rentable              23
2     Habitation  Non rentable             218
3     Habitation      Rentable              24
4          Santé  Non rentable             231
5          Santé      Rentable              23
6            Vie  Non rentable             217
7            Vie      Rentable              26

In [ ]:
fig_rentable_type = px.bar(
    data_assurance_grouped_rentable_type,
    x="type_assurance",
    y="nombre_clients",
    color="rentabilite",   # séparation des barres
    barmode="group",      # barres côte à côte
    title="Répartition de rentabilité par type d'assurance",
    labels={
        "type_assurance": "Type d'assurance",
        "rentabilite": "Rentabilité"
    },
    text_auto=True
)

fig_rentable_type.update_layout(
    yaxis_title="Nombre de clients"
)

fig_rentable_type.show()